// 🔥 CONFIGURATION DE NAVIGATION GÉNÉRÉE 🔥
// Remplacez cette constante par le résultat JSON de votre génération de navigation

export const NAV_CONFIG ={
  "functionCode": "ADMIN",
  "functionDescription": "Navigation pour ADMIN",
  "navMain": [
    {
      "title": "Gestion des clients",
      "url": "/customers",
      "items": [
        {
          "title": "Clients",
          "url": "/customers",
          "icon": "RiUserLine",
          "description": "cette fonctionnalité permet de gerer toutes les informations en rapport avec les clients",
          "actions": [
            {
              "code": "CREATE_CUSTOMER",
              "title": "creer un client",
              "description": "cette action permet de creer un client"
            },
            {
              "code": "DELETE_CUSTOMER",
              "title": "supprimer un client",
              "description": "cette action permet de supprimer un client"
            },
            {
              "code": "GET_CUSTOMER_ID",
              "title": "afficher un client",
              "description": "cete action permet d'afficher un client"
            },
            {
              "code": "GET_CUSTOMERS",
              "title": "afficher les clients",
              "description": "cette action permet de lister les clients"
            },
            {
              "code": "UPDATE_CUSTOMER",
              "title": "modifier un client",
              "description": "cette action permet de modifier un client"
            }
          ],
          "fonctionnaliteCode": "GESTION_CUSTOMER",
          "moduleCode": "3"
        }
      ]
    },
    {
      "title": "Gestion des comptes",
      "url": "/accounts",
      "items": [
        {
          "title": "Comptes",
          "url": "/accounts",
          "icon": "RiFolderLine",
          "description": "cette fonctionnalité permet de gerer les comptes des clients",
          "actions": [
            {
              "code": "CREATE_ACCOUNT",
              "title": "creer un compte",
              "description": "cette action permet de creer un compte pour un client"
            },
            {
              "code": "DELETE_ACCOUNT",
              "title": "supprimer compte",
              "description": "cette action permet de supprimer un compte"
            },
            {
              "code": "GET_ACCOUNT_ID",
              "title": "voir son compte",
              "description": "cette action vous permet de voir les données en rapport avec votre compte"
            },
            {
              "code": "GET_ACCOUNTS",
              "title": "afficher les comptes",
              "description": "cette action permet d'afficher les comptes des clients"
            },
            {
              "code": "UPDATE_ACCOUNT",
              "title": "modifier un compte",
              "description": "cette action permet de modifier un compte pour un client"
            }
          ],
          "fonctionnaliteCode": "GESTION_ACCOUNT",
          "moduleCode": "2"
        }
      ]
    },
    {
      "title": "Gestion utilisateurs",
      "url": "/users",
      "items": [
        {
          "title": "utilisateurs",
          "url": "/users",
          "icon": "RiTeamLine",
          "description": "Cette fonctionnalité permet de gerer les utilisateurs ",
          "actions": [
            {
              "code": "CREATE_USER",
              "title": "creer un utilisateur",
              "description": "cette action permet de creer un utilisateur"
            },
            {
              "code": "DELETE_USER",
              "title": "supprimer utilisateur",
              "description": "cette action permet de supprimer un  utilisateur"
            },
            {
              "code": "GET_USER_ID",
              "title": "afficher un utilisateur",
              "description": "cette action permet d'afficher un utilisateur"
            },
            {
              "code": "GET_USERS",
              "title": "afficher les utilisateurs",
              "description": "cette action permet d'afficher la liste des utilisateurs"
            },
            {
              "code": "UPDATE_USER",
              "title": "modifer utilisateur",
              "description": "cette action permet de modifier un utilisateur"
            }
          ],
          "fonctionnaliteCode": "GESTION_USER",
          "moduleCode": "1"
        }
      ]
    }
  ]
}
// Mapping des icônes Remix
import {
  RiApps2Line,
  RiArrowRightLine,
  RiSortAsc,
  RiPrinterLine,
  RiFlightTakeoffLine,
  RiEmotionHappyLine,
  RiBankCardLine,
  RiScalesLine,
  RiLayoutLeftLine,
  RiFlashlightFill,
  RiPlayLine,
  RiUserSettingsLine,
  RiSettings3Line,
  RiDashboardLine,
  RiDatabase2Line,
  RiCloudLine,
  RiShieldCheckLine,
  RiLockLine,
  RiKeyLine,
  RiUserLine,
  RiTeamLine,
  RiFileTextLine,
  RiBarChartLine,
  RiPieChartLine,
  RiLineChartLine,
  RiMailLine,
  RiNotificationLine,
  RiCalendarLine,
  RiTimeLine,
  RiMapPinLine,
  RiGlobalLine,
  RiSearchLine,
  RiFilterLine,
  RiRefreshLine,
  RiDownloadLine,
  RiUploadLine,
  RiShareLine,
  RiCameraLine,
  RiImageLine,
  RiVideoLine,
  RiMusicLine,
  RiFolderLine,
  RiFileLine,
  RiArchiveLine,
  RiInboxLine,
  RiSendPlaneLine,
  RiReplyLine,
  RiEditLine,
  RiDeleteBinLine,
  RiAddLine,
  RiSubtractLine,
  RiCloseLine,
  RiCheckLine,
  RiStarLine,
  RiHeartLine,
  RiThumbUpLine,
  RiBookmarkLine,
  RiFlagLine,
  RiEyeLine,
  RiEyeOffLine,
  RiVolumeUpLine,
  RiVolumeDownLine,
  RiVolumeMuteLine,
  RiPhoneLine,
  RiSmartphoneLine,
  RiComputerLine,
  RiTvLine,
  RiGamepadLine,
  RiHeadphoneLine,
  RiMicLine,
  RiWifiLine,
  RiBluetoothLine,
  RiBatteryLine,
  RiFlashlightLine,
  RiSunLine,
  RiMoonLine,
  RiThunderstormsLine,
  RiRainyLine,
  RiSnowyLine,
  RiWindyLine,
  RiFireLine,
  RiLeafLine,
  RiSeedlingLine,
  RiTreeLine,
  RiFlowerLine,
  RiBugLine,
  RiCarLine,
  RiBusLine,
  RiTruckLine,
  RiPlaneLine,
  RiRocketLine,
  RiShipLine,
  RiBikeLine,
  RiWalkLine,
  RiRunLine,
  RiFootballLine,
  RiBasketballLine,
  RiPingPongLine,
  RiBoxingLine,
  RiMedal2Line,
  RiTrophyLine,
  RiAwardLine,
  RiGiftLine,
  RiCupLine,
  RiRestaurantLine,
  RiHammerLine,
  RiToolsLine,
  RiScissorsLine,
  RiRulerLine,
  RiCompassLine,
  RiCalculatorLine,
  RiMicroscopeLine,
  RiFlaskLine,
  RiTestTubeLine,
  RiCapsuleLine,
  RiStethoscopeLine,
  RiFirstAidKitLine,
  RiHospitalLine,
  RiPulseLine,
  RiMentalHealthLine,
  RiShoppingCartLine,
  RiShoppingBagLine,
  RiStore2Line,
  RiBankLine,
  RiMoneyDollarCircleLine,
  RiCoinLine,
  RiWalletLine,
  RiSafeLine,
  RiScales2Line,
  RiGovernmentLine,
  RiPoliceCarLine,
  RiSchoolLine,
  RiBookLine,
  RiGraduationCapLine,
  RiPencilLine,
  RiPaintBrushLine,
  RiPaletteLine,
  RiArtboardLine,
  RiDraftLine,
  RiLayoutLine,
  RiGridLine,
  RiTableLine,
  RiMenuLine,
  RiMore2Line,
  RiLoader4Line
} from "@remixicon/react"

const iconList = [
  { name: "RiApps2Line", icon: RiApps2Line, category: "Interface" },
  { name: "RiFlashlightFill", icon: RiFlashlightFill, category: "Interface" },
  { name: "RiPlayLine", icon: RiPlayLine, category: "Media" },
  { name: "RiUserSettingsLine", icon: RiUserSettingsLine, category: "User" },
  { name: "RiSettings3Line", icon: RiSettings3Line, category: "Interface" },
  { name: "RiDashboardLine", icon: RiDashboardLine, category: "Interface" },
  { name: "RiDatabase2Line", icon: RiDatabase2Line, category: "Data" },
  { name: "RiCloudLine", icon: RiCloudLine, category: "Weather" },
  { name: "RiShieldCheckLine", icon: RiShieldCheckLine, category: "Security" },
  { name: "RiLockLine", icon: RiLockLine, category: "Security" },
  { name: "RiKeyLine", icon: RiKeyLine, category: "Security" },
  { name: "RiUserLine", icon: RiUserLine, category: "User" },
  { name: "RiTeamLine", icon: RiTeamLine, category: "User" },
  { name: "RiFileTextLine", icon: RiFileTextLine, category: "Files" },
  { name: "RiBarChartLine", icon: RiBarChartLine, category: "Charts" },
  { name: "RiPieChartLine", icon: RiPieChartLine, category: "Charts" },
  { name: "RiLineChartLine", icon: RiLineChartLine, category: "Charts" },
  { name: "RiMailLine", icon: RiMailLine, category: "Communication" },
  { name: "RiNotificationLine", icon: RiNotificationLine, category: "Communication" },
  { name: "RiCalendarLine", icon: RiCalendarLine, category: "Time" },
  { name: "RiTimeLine", icon: RiTimeLine, category: "Time" },
  { name: "RiMapPinLine", icon: RiMapPinLine, category: "Location" },
  { name: "RiGlobalLine", icon: RiGlobalLine, category: "Location" },
  { name: "RiSearchLine", icon: RiSearchLine, category: "Interface" },
  { name: "RiFilterLine", icon: RiFilterLine, category: "Interface" },
  { name: "RiSortAsc", icon: RiSortAsc, category: "Interface" },
  { name: "RiRefreshLine", icon: RiRefreshLine, category: "Interface" },
  { name: "RiDownloadLine", icon: RiDownloadLine, category: "Transfer" },
  { name: "RiUploadLine", icon: RiUploadLine, category: "Transfer" },
  { name: "RiShareLine", icon: RiShareLine, category: "Transfer" },
  { name: "RiPrinterLine", icon: RiPrinterLine, category: "Office" },
  { name: "RiCameraLine", icon: RiCameraLine, category: "Media" },
  { name: "RiImageLine", icon: RiImageLine, category: "Media" },
  { name: "RiVideoLine", icon: RiVideoLine, category: "Media" },
  { name: "RiMusicLine", icon: RiMusicLine, category: "Media" },
  { name: "RiFolderLine", icon: RiFolderLine, category: "Files" },
  { name: "RiFileLine", icon: RiFileLine, category: "Files" },
  { name: "RiArchiveLine", icon: RiArchiveLine, category: "Files" },
  { name: "RiInboxLine", icon: RiInboxLine, category: "Communication" },
  { name: "RiSendPlaneLine", icon: RiSendPlaneLine, category: "Communication" },
  { name: "RiReplyLine", icon: RiReplyLine, category: "Communication" },
  { name: "RiArrowRightLine", icon: RiArrowRightLine, category: "Communication" },
  { name: "RiEditLine", icon: RiEditLine, category: "Interface" },
  { name: "RiDeleteBinLine", icon: RiDeleteBinLine, category: "Interface" },
  { name: "RiAddLine", icon: RiAddLine, category: "Interface" },
  { name: "RiSubtractLine", icon: RiSubtractLine, category: "Interface" },
  { name: "RiCloseLine", icon: RiCloseLine, category: "Interface" },
  { name: "RiCheckLine", icon: RiCheckLine, category: "Interface" },
  { name: "RiStarLine", icon: RiStarLine, category: "Social" },
  { name: "RiHeartLine", icon: RiHeartLine, category: "Social" },
  { name: "RiThumbUpLine", icon: RiThumbUpLine, category: "Social" },
  { name: "RiBookmarkLine", icon: RiBookmarkLine, category: "Social" },
  { name: "RiFlagLine", icon: RiFlagLine, category: "Social" },
  { name: "RiEyeLine", icon: RiEyeLine, category: "Interface" },
  { name: "RiEyeOffLine", icon: RiEyeOffLine, category: "Interface" },
  { name: "RiVolumeUpLine", icon: RiVolumeUpLine, category: "Media" },
  { name: "RiVolumeDownLine", icon: RiVolumeDownLine, category: "Media" },
  { name: "RiVolumeMuteLine", icon: RiVolumeMuteLine, category: "Media" },
  { name: "RiPhoneLine", icon: RiPhoneLine, category: "Communication" },
  { name: "RiSmartphoneLine", icon: RiSmartphoneLine, category: "Device" },
  { name: "RiComputerLine", icon: RiComputerLine, category: "Device" },
  { name: "RiTvLine", icon: RiTvLine, category: "Device" },
  { name: "RiGamepadLine", icon: RiGamepadLine, category: "Entertainment" },
  { name: "RiHeadphoneLine", icon: RiHeadphoneLine, category: "Device" },
  { name: "RiMicLine", icon: RiMicLine, category: "Device" },
  { name: "RiWifiLine", icon: RiWifiLine, category: "Connectivity" },
  { name: "RiBluetoothLine", icon: RiBluetoothLine, category: "Connectivity" },
  { name: "RiBatteryLine", icon: RiBatteryLine, category: "Device" },
  { name: "RiFlashlightLine", icon: RiFlashlightLine, category: "Utility" },
  { name: "RiSunLine", icon: RiSunLine, category: "Weather" },
  { name: "RiMoonLine", icon: RiMoonLine, category: "Weather" },
  { name: "RiThunderstormsLine", icon: RiThunderstormsLine, category: "Weather" },
  { name: "RiRainyLine", icon: RiRainyLine, category: "Weather" },
  { name: "RiSnowyLine", icon: RiSnowyLine, category: "Weather" },
  { name: "RiWindyLine", icon: RiWindyLine, category: "Weather" },
  { name: "RiFireLine", icon: RiFireLine, category: "Nature" },
  { name: "RiLeafLine", icon: RiLeafLine, category: "Nature" },
  { name: "RiSeedlingLine", icon: RiSeedlingLine, category: "Nature" },
  { name: "RiTreeLine", icon: RiTreeLine, category: "Nature" },
  { name: "RiFlowerLine", icon: RiFlowerLine, category: "Nature" },
  { name: "RiBugLine", icon: RiBugLine, category: "Nature" },
  { name: "RiFlightTakeoffLine", icon: RiFlightTakeoffLine, category: "Transport" },
  { name: "RiEmotionHappyLine", icon: RiEmotionHappyLine, category: "Emotion" },
  { name: "RiCarLine", icon: RiCarLine, category: "Transport" },
  { name: "RiBusLine", icon: RiBusLine, category: "Transport" },
  { name: "RiTruckLine", icon: RiTruckLine, category: "Transport" },
  { name: "RiPlaneLine", icon: RiPlaneLine, category: "Transport" },
  { name: "RiRocketLine", icon: RiRocketLine, category: "Transport" },
  { name: "RiShipLine", icon: RiShipLine, category: "Transport" },
  { name: "RiBikeLine", icon: RiBikeLine, category: "Transport" },
  { name: "RiWalkLine", icon: RiWalkLine, category: "Activity" },
  { name: "RiRunLine", icon: RiRunLine, category: "Activity" },
  { name: "RiFootballLine", icon: RiFootballLine, category: "Sports" },
  { name: "RiBasketballLine", icon: RiBasketballLine, category: "Sports" },
  { name: "RiPingPongLine", icon: RiPingPongLine, category: "Sports" },
  { name: "RiBoxingLine", icon: RiBoxingLine, category: "Sports" },
  { name: "RiMedal2Line", icon: RiMedal2Line, category: "Achievement" },
  { name: "RiTrophyLine", icon: RiTrophyLine, category: "Achievement" },
  { name: "RiAwardLine", icon: RiAwardLine, category: "Achievement" },
  { name: "RiGiftLine", icon: RiGiftLine, category: "Shopping" },
  { name: "RiCupLine", icon: RiCupLine, category: "Food" },
  { name: "RiRestaurantLine", icon: RiRestaurantLine, category: "Food" },
  { name: "RiHammerLine", icon: RiHammerLine, category: "Tools" },
  { name: "RiToolsLine", icon: RiToolsLine, category: "Tools" },
  { name: "RiScissorsLine", icon: RiScissorsLine, category: "Tools" },
  { name: "RiRulerLine", icon: RiRulerLine, category: "Tools" },
  { name: "RiCompassLine", icon: RiCompassLine, category: "Tools" },
  { name: "RiCalculatorLine", icon: RiCalculatorLine, category: "Tools" },
  { name: "RiMicroscopeLine", icon: RiMicroscopeLine, category: "Science" },
  { name: "RiFlaskLine", icon: RiFlaskLine, category: "Science" },
  { name: "RiTestTubeLine", icon: RiTestTubeLine, category: "Science" },
  { name: "RiCapsuleLine", icon: RiCapsuleLine, category: "Health" },
  { name: "RiStethoscopeLine", icon: RiStethoscopeLine, category: "Health" },
  { name: "RiFirstAidKitLine", icon: RiFirstAidKitLine, category: "Health" },
  { name: "RiHospitalLine", icon: RiHospitalLine, category: "Health" },
  { name: "RiPulseLine", icon: RiPulseLine, category: "Health" },
  { name: "RiMentalHealthLine", icon: RiMentalHealthLine, category: "Health" },
  { name: "RiShoppingCartLine", icon: RiShoppingCartLine, category: "Shopping" },
  { name: "RiShoppingBagLine", icon: RiShoppingBagLine, category: "Shopping" },
  { name: "RiStore2Line", icon: RiStore2Line, category: "Shopping" },
  { name: "RiBankLine", icon: RiBankLine, category: "Finance" },
  { name: "RiMoneyDollarCircleLine", icon: RiMoneyDollarCircleLine, category: "Finance" },
  { name: "RiCoinLine", icon: RiCoinLine, category: "Finance" },
  { name: "RiBankCardLine", icon: RiBankCardLine, category: "Finance" },
  { name: "RiWalletLine", icon: RiWalletLine, category: "Finance" },
  { name: "RiSafeLine", icon: RiSafeLine, category: "Finance" },
  { name: "RiScales2Line", icon: RiScales2Line, category: "Legal" },
  { name: "RiScalesLine", icon: RiScalesLine, category: "Legal" },
  { name: "RiGovernmentLine", icon: RiGovernmentLine, category: "Government" },
  { name: "RiPoliceCarLine", icon: RiPoliceCarLine, category: "Government" },
  { name: "RiSchoolLine", icon: RiSchoolLine, category: "Education" },
  { name: "RiBookLine", icon: RiBookLine, category: "Education" },
  { name: "RiGraduationCapLine", icon: RiGraduationCapLine, category: "Education" },
  { name: "RiPencilLine", icon: RiPencilLine, category: "Office" },
  { name: "RiPaintBrushLine", icon: RiPaintBrushLine, category: "Creative" },
  { name: "RiPaletteLine", icon: RiPaletteLine, category: "Creative" },
  { name: "RiArtboardLine", icon: RiArtboardLine, category: "Creative" },
  { name: "RiDraftLine", icon: RiDraftLine, category: "Creative" },
  { name: "RiLayoutLine", icon: RiLayoutLine, category: "Interface" },
  { name: "RiGridLine", icon: RiGridLine, category: "Interface" },
  { name: "RiTableLine", icon: RiTableLine, category: "Interface" },
  { name: "RiLayoutLeftLine", icon: RiLayoutLeftLine, category: "Interface" },
  { name: "RiMenuLine", icon: RiMenuLine, category: "Interface" },
  { name: "RiMore2Line", icon: RiMore2Line, category: "Interface" },
  { name: "RiLoader4Line", icon: RiLoader4Line, category: "Interface" }
]

export const ICON_MAP: Record<string, any> = iconList.reduce((acc, item) => {
  acc[item.name] = item.icon;
  return acc;
}, {} as Record<string, any>);